apiVersion: v1
kind: Service
metadata:
  name: tinyhttp-wireguard
  namespace: wireguard-proxy
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.205"
spec:
  ports:
  - name: "http"
    port: 8888
    targetPort: 8888
  selector:
    app.kubernetes.io/name: tinyhttp-wireguard
  type: LoadBalancer
